"""Add Project model

Revision ID: d2c3cedaeb42
Revises: 
Create Date: 2025-07-04 12:24:48.457898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c3cedaeb42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technologies', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('github_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('live_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('date_added')
        batch_op.drop_column('project_url')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('project_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('image')
        batch_op.drop_column('live_link')
        batch_op.drop_column('github_link')
        batch_op.drop_column('technologies')

    # ### end Alembic commands ###
